/** Canvas node types that expose materializable model weights for the Observable factory. */
export const OBSERVABLE_MODEL_NODE_TYPES = new Set([
  "mlp_model",
  "gated_mlp_model",
  "moe_mlp_model",
  "mlp_token_model",
  "gated_mlp_token_model",
  "moe_mlp_token_model",
  "numeric_transformer_model",
  "numeric_hyena_model",
  "mpp_spatiotemporal_model",
  "afno_lite_spatiotemporal_model",
  "transformer_token_model",
  "transformer_multi_token_model",
  "kan_model",
  "residual_ln_model",
  "attention_only_model",
  "linear_attention_model",
  "diagonal_ssm_token_model",
  "rwkv_time_mix_token_model",
  "hyena_like_conv_model",
  "slot_attention_token_model",
  "diffusion_score_model",
  "crl_residual_mlp",
  "combined_model",
  "linear_layer",
  "activation_layer",
  "layer_norm_layer",
  "rms_norm_layer",
  "embedding_layer",
  "unembedding_layer",
  "absolute_pos_embed_layer",
  "rotary_embed_layer",
  "local_mixing_layer",
  "afno_patch_embed_layer",
  "afno_spectral_mixer_layer",
  "afno_encoder_block_layer",
  "afno_patch_decode_layer",
  "model_checkpoint",
]);

export function isObservableModelNodeType(type: string | undefined | null): boolean {
  return OBSERVABLE_MODEL_NODE_TYPES.has(String(type ?? ""));
}
